Check “ldd” output

diff --git a/roopwn b/roopwn
--- a/roopwn
+++ b/roopwn
@@ -49,22 +49,35 @@ main() {
     unset WORK
     trap onexit EXIT
     WORK="$(mktemp --tmpdir --directory roopwn.XXXXXXXXXX)"
-    echo >&2 "Temporarily extracting:" "$pkg"
-    local files file deps
+    echo >&2 "Analysing:" "$pkg"
+    local files file deps missing fail
     files="$(tar xvf "$pkg" -C "$WORK" --exclude ".*" --anchored)"
     while read -r file; do
-        file="$WORK/$file"
+        workfile="$WORK/$file"
         if ! {
-            test -x "$file" &&
-            deps="$(ldd -- "$file" 2> /dev/null)"
+            test -x "$workfile" &&
+            deps="$(ldd -- "$workfile" 2> /dev/null)"
         } then
             continue
+        fi
+        if missing="$(
+            grep ' => not found$' << INPUT
+$deps
+INPUT
+        )"; then
+            echo >&2 "$file:"
+            echo >&2 "$missing"
+            fail=set
         fi
     done << INPUT
 $files
 INPUT
     rm -rf -- "$WORK"
     unset WORK
+    
+    if test -n "${fail-}"; then
+        return 1
+    fi
     
     pacman --upgrade "$pkg"
 }
